### ISSUE TITLE
Improved powerup for last place player

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/hooksharks#194]

**Comment by LuizGyro** [comment]
Does this mean a better version of the powerup the player gets? Or does he get powerups from a reduced list of powerups that we consider "better"?

**Comment by ArthurTui** [comment]
The original idea was to have a chance for the last player to get a better version of the powerup he gets.

On second thought this would only make matters worse when the player on the lead gets ahead, since this improved powerup would almost never affect him, making it even harder to perform comebacks.

**Comment by rilifon** [comment]
On last meeting we discussed to not do this anymore
