### ISSUE TITLE
How dinamic should Race Mode be?

### ISSUE THREAD

**Issue by Detril** [MarvellousSoft/hooksharks#36]
The split screen denotes a more prolonged, traditional race game, but it is the intended gameplay?

If the Race Mode is decided to be extremely quick paced and with perma-death within each round, maybe a small map with a shared screen would be more suited.

So which is it, a more traditional race? Quick paced onslaught? Both separately?

**Comment by rilifon** [comment]
Given the arena mode, and the overall feel I got (and enjoyed) from those
matches, I'm more inclined to fast paced action.
We still should test it to make sure it plays great (as I think is with the
arena), but I vote to implement first this quick-pace racing mode before
trying a more slow, traditional racing game type.

Em seg, 11 de fev de 2019 18:24, Andre Ferrari Moukarzel <
notifications@github.com> escreveu:

**Comment by ArthurTui** [comment]
I don't think being more traditional and with bigger stages would mean being less fast paced. If the racing part of the race doesn't matter as much then it will just be like arena mode with an additional win condition.

**Comment by rilifon** [comment]
But the race part should matter! I don't follow how smaller stages and
several laps makes the race part not matter as much. But yes, bigger stages
does mean less interaction from players that are farther apart, while
closer stages mean more chaos, that would be fitting given the idea of
having itens and stuff.

I think for the race mode, perma-death could be interesting, but players
could have hp, or something like that (kind of like f-zero). It could bring
some cool dynamics where first players are one lap ahead, but still
side-by-side with last position players, but they could all join to start
hooking and messing with the best players, creating a self-balance
ecosystem.

Em ter, 12 de fev de 2019 às 15:00, Arthur <notifications@github.com>
escreveu:

**Comment by rilifon** [comment]
Also, this notion of bigger and smaller stages is pretty relative. We could
be thinking the same size of stages. My main point is I think quick
matches, maybe 4-5 minutes long, would be more interesting than a 15+
minute long race.

Em ter, 12 de fev de 2019 às 16:20, Ricardo F <pudimdefrutas@gmail.com>
escreveu:

**Comment by LuizGyro** [comment]
I think races should be fast-paced, and have multiple "rounds", like Arena Mode, but should have a distinct feel to it. Regardless of if we have big or small racing courses, if the main mechanic incentivized is still destroying other players, then what @ArthurTui said becomes true, and the racing mode is kinda pointless.

As @rilifon said, we could look at F-Zero as a good example: the main appeal of the game (in my opinion) is skilfully navigating through decently-sized courses, while keeping in the back of your head that you can die and permanently lose, if you are not careful enough. This does not matter much, because races in F-Zero tend to last between 3 to 5 minutes, so the destroyed player does not feel too left out or frustrated, even in the case of being destroyed, but is reminded of this lose condition.
